### ISSUE TITLE
Question about A-pose rendering

### ISSUE THREAD

**Issue by zeng-yifei** [songrise/AvatarCraft#11]
Hey, really happy to see that AvatarCraft is finally released.

I observed most of the demos are present as the T-pose. Meanwhile, there are some A-pose demonstrations in Fig.6 of the paper. I wonder how to render an A-pose image of a given model. Do I need to prepare a corresponding motion pkl? Or using some SMPL Parameters would just work?

Hope for your reply :-)

**Comment by songrise** [comment]
hi, the A-pose (stand pose) is taken from [AvatarCLIP](https://github.com/hongfz16/AvatarCLIP/blob/main/AvatarGen/ShapeGen/output/stand_pose.npy). I have just uploaded to this repo [here](https://github.com/songrise/AvatarCraft/blob/main/data/stand_pose.npy). You can load the pose parameters and set it as the articulation target, then you can get what is shown in our Fig. 6.

**Comment by songrise** [comment]
> hi, the A-pose (stand pose) is taken from AvatarCLIP. The original file is [here](https://github.com/hongfz16/AvatarCLIP/blob/main/AvatarGen/AppearanceGen/pretrained_models/zero_beta_stand_pose.pth). You can load the pose parameters and set it as the articulation target, then you can get what is shown in our Fig. 6.

Besides, in articulation code we use .npy for pose articulation, and I remember we have remove the rotation of the first joint. The processed file could be found [here](https://github.com/songrise/AvatarCraft/blob/main/data/stand_pose.npy).

**Comment by zeng-yifei** [comment]
Thank you very much for your quick reply! The problem is now tackled with the data file.

BTW, there is a minor difference between the instructions and the actual file name.

In readme instructions, it uses `python render_w**ra**p.py` to animate the model, but the actual file name is `render_w**ar**p.py`. Hope it will be modified. :-)

**Comment by songrise** [comment]
> Thank you very much for your quick reply! The problem is now tackled with the data file.
> 
> BTW, there is a minor difference between the instructions and the actual file name.
> 
> In readme instructions, it uses `python render_w**ra**p.py` to animate the model, but the actual file name is `render_w**ar**p.py`. Hope it will be modified. :-)

thanks for your reply. The typo has been fixed.
