### ISSUE TITLE
The paper link of the project page is redirected to Nerfie

### ISSUE THREAD

**Issue by zeng-yifei** [songrise/AvatarCraft#2]
Both paper button and arxiv button in the project page [here](https://avatar-craft.github.io/) is linked with Nerfie. I wonder whether it is a mistake or the paper is just not available for reading yet. If the situation is the latter one, then when will the paper be released? Hope for your answer : ) 

BTW, it is a REALLY  great work and demo. Your team's work is always superising me

**Comment by songrise** [comment]
Hi, thanks for your interest in this project. The paper is just not available at this moment. We will upload it to arxiv in this week, and I will replace the link at that time :).

**Comment by zeng-yifei** [comment]
Oh, that's great. Can't wait to read the paper!
