### ISSUE TITLE
Hardcoded inputs in render_warp.py

### ISSUE THREAD

**Issue by kyusuncho** [songrise/AvatarCraft#6]
Hi, thanks for the great work. 

However, I cannot get the articulation code to work, as there seem to be some missing files, including "data/stand_pose.npy", "data/smpl_da_512" and 'data/smplx/smpl_uv.obj'.

Are there any more updates planned? 
Thanks.

**Comment by songrise** [comment]
Hi, thanks for your reply. Try pull the newest version. For the smpl_uv.obj, you need to download it from SMPL website and put it under the `data/`. If you still cannot run the articulation, please let me know.
